export function showValidationError(inputElement, message) {
    // Add a class to the input element to change its border color to red
    inputElement.classList.add("invalid-input");
    // Show the validation error message to the user
    const errorMessageElement = document.createElement("div");
    errorMessageElement.className = "error-message";
    errorMessageElement.style.color = "red";
    errorMessageElement.innerText = message;
  
    // Check if an error message is already displayed and remove it if so
    inputElement.closest("label").querySelector(".error-message")?.remove();
    if (
      inputElement.classList.contains("phoneInput") &&
      inputElement.closest(".iti")
    ) {
      inputElement.closest(".iti").after(errorMessageElement);
    } else {
      inputElement.after(errorMessageElement);
    }
  }
  

// Remove the validation error styles and messages when the input is corrected
document.addEventListener("input", (event) => {
  if (event.target.tagName === "INPUT") {
    const inputElement = event.target;
    inputElement.classList.remove("invalid-input");
    inputElement.closest("label")?.querySelector(".error-message")?.remove();
  }
});


  // function isValidDate(dateString) {
  //   const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  //   return dateRegex.test(dateString);
  // }
  
  // function isValidCountry(country) {
  //   // Validate that the country input is exactly two characters
  //   if (country.length !== 2) {
  //     return false;
  //   }
  //   // List of allowed country codes
  //   const allowedCountryCodes = [
  //     "AF",
  //     "AX",
  //     "AL",
  //     "DZ",
  //     "AS",
  //     "AD",
  //     "AO",
  //     "AI",
  //     "AQ",
  //     "AG",
  //     "AR",
  //     "AM",
  //     "AW",
  //     "AU",
  //     "AT",
  //     "AZ",
  //     "BS",
  //     "BH",
  //     "BD",
  //     "BB",
  //     "BY",
  //     "BE",
  //     "BZ",
  //     "BJ",
  //     "BM",
  //     "BT",
  //     "BO",
  //     "BQ",
  //     "BA",
  //     "BW",
  //     "BV",
  //     "BR",
  //     "IO",
  //     "BN",
  //     "BG",
  //     "BF",
  //     "BI",
  //     "KH",
  //     "CM",
  //     "CA",
  //     "CV",
  //     "KY",
  //     "CF",
  //     "TD",
  //     "CL",
  //     "CN",
  //     "CX",
  //     "CC",
  //     "CO",
  //     "KM",
  //     "CG",
  //     "CD",
  //     "CK",
  //     "CR",
  //     "CI",
  //     "HR",
  //     "CU",
  //     "CW",
  //     "CY",
  //     "CZ",
  //     "DK",
  //     "DJ",
  //     "DM",
  //     "DO",
  //     "EC",
  //     "EG",
  //     "SV",
  //     "GQ",
  //     "ER",
  //     "EE",
  //     "ET",
  //     "FK",
  //     "FO",
  //     "FJ",
  //     "FI",
  //     "FR",
  //     "GF",
  //     "PF",
  //     "TF",
  //     "GA",
  //     "GM",
  //     "GE",
  //     "DE",
  //     "GH",
  //     "GI",
  //     "GR",
  //     "GL",
  //     "GD",
  //     "GP",
  //     "GU",
  //     "GT",
  //     "GG",
  //     "GN",
  //     "GW",
  //     "GY",
  //     "HT",
  //     "HM",
  //     "VA",
  //     "HN",
  //     "HK",
  //     "HU",
  //     "IS",
  //     "IN",
  //     "ID",
  //     "IR",
  //     "IQ",
  //     "IE",
  //     "IM",
  //     "IT",
  //     "JM",
  //     "JP",
  //     "JE",
  //     "JO",
  //     "KZ",
  //     "KE",
  //     "KI",
  //     "KP",
  //     "KR",
  //     "XK",
  //     "KW",
  //     "KG",
  //     "LA",
  //     "LV",
  //     "LB",
  //     "LS",
  //     "LR",
  //     "LY",
  //     "LI",
  //     "LT",
  //     "LU",
  //     "MO",
  //     "MK",
  //     "MG",
  //     "MW",
  //     "MY",
  //     "MV",
  //     "ML",
  //     "MT",
  //     "MH",
  //     "MQ",
  //     "MR",
  //     "MU",
  //     "YT",
  //     "MX",
  //     "FM",
  //     "MD",
  //     "MC",
  //     "MN",
  //     "ME",
  //     "MS",
  //     "MA",
  //     "MZ",
  //     "MM",
  //     "NA",
  //     "NR",
  //     "NP",
  //     "NL",
  //     "AN",
  //     "NC",
  //     "NZ",
  //     "NI",
  //     "NE",
  //     "NG",
  //     "NU",
  //     "NF",
  //     "MP",
  //     "NO",
  //     "OM",
  //     "PK",
  //     "PW",
  //     "PS",
  //     "PA",
  //     "PG",
  //     "PY",
  //     "PE",
  //     "PH",
  //     "PN",
  //     "PL",
  //     "PT",
  //     "PR",
  //     "QA",
  //     "RE",
  //     "RO",
  //     "RU",
  //     "RW",
  //     "BL",
  //     "SH",
  //     "KN",
  //     "LC",
  //     "MF",
  //     "PM",
  //     "VC",
  //     "WS",
  //     "SM",
  //     "ST",
  //     "SA",
  //     "SN",
  //     "RS",
  //     "SC",
  //     "SL",
  //     "SG",
  //     "SX",
  //     "SK",
  //     "SI",
  //     "SB",
  //     "SO",
  //     "ZA",
  //     "GS",
  //     "SS",
  //     "ES",
  //     "LK",
  //     "SD",
  //     "SR",
  //     "SJ",
  //     "SZ",
  //     "SE",
  //     "CH",
  //     "SY",
  //     "TW",
  //     "TJ",
  //     "TZ",
  //     "TH",
  //     "TL",
  //     "TG",
  //     "TK",
  //     "TO",
  //     "TT",
  //     "TN",
  //     "TR",
  //     "TM",
  //     "TC",
  //     "TV",
  //     "UG",
  //     "UA",
  //     "AE",
  //     "GB",
  //     "US",
  //     "UM",
  //     "UY",
  //     "UZ",
  //     "VU",
  //     "VE",
  //     "VN",
  //     "VG",
  //     "VI",
  //     "WF",
  //     "EH",
  //     "YE",
  //     "ZM",
  //     "ZW",
  //   ];
  
  //   return allowedCountryCodes.includes(country.toUpperCase());
  // }